package com.masterlearning.platform.modules.program.controller;
import com.masterlearning.platform.common.api.ApiResponse; import com.masterlearning.platform.modules.program.dto.request.*; import com.masterlearning.platform.modules.program.entity.*; import com.masterlearning.platform.modules.program.repository.*; import com.masterlearning.platform.modules.organization.repository.OrganizationRepository; import com.masterlearning.platform.modules.course.repository.CourseRepository; import jakarta.persistence.EntityNotFoundException; import jakarta.validation.Valid; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/v1/programs") public class ProgramController {
 private final ProgramRepository programs; private final LearningPathRepository paths; private final LearningPathCourseRepository pathCourses; private final OrganizationRepository organizations; private final CourseRepository courses; private final com.masterlearning.platform.modules.organization.security.OrganizationAuthorizationService organizationAuthorization;
 public ProgramController(ProgramRepository p,LearningPathRepository lp,LearningPathCourseRepository lpc,OrganizationRepository o,CourseRepository c,com.masterlearning.platform.modules.organization.security.OrganizationAuthorizationService oa){programs=p;paths=lp;pathCourses=lpc;organizations=o;courses=c;organizationAuthorization=oa;}
 @GetMapping("/organization/{organizationId}") @PreAuthorize("hasRole('SUPER_ADMIN') or @organizationAuthorization.canAccessOrganization(#organizationId)") public ApiResponse<List<Map<String,Object>>> organizationPrograms(@PathVariable UUID organizationId){var list=programs.findByOrganizationIdOrderByTitleAsc(organizationId);var out=list.stream().map(p->Map.<String,Object>of("id",p.getId(),"title",p.getTitle(),"slug",p.getSlug(),"description",p.getDescription()==null?"":p.getDescription(),"status",p.getStatus().name(),"organizationId",p.getOrganization()==null?null:p.getOrganization().getId())).toList();return ApiResponse.success("Organization programs retrieved",out);}
 @PostMapping @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','INSTRUCTOR','ORG_ADMIN')") public ApiResponse<Map<String,Object>> create(@Valid @RequestBody CreateProgramRequest r){if(programs.findBySlug(r.slug()).isPresent())throw new IllegalArgumentException("Program slug already exists");var o=r.organizationId()==null?null:organizations.findById(r.organizationId()).orElseThrow(()->new EntityNotFoundException("Organization not found"));if (!isSuperAdmin() && (o == null || !organizationAuthorization.canAccessOrganization(o.getId()))) throw new AccessDeniedException("You do not have access to this organization"); var p=programs.save(new Program(r.title(),r.slug(),r.description(),o));return ApiResponse.success("Program created",Map.of("id",p.getId(),"title",p.getTitle()));}
 @PostMapping("/{programId}/paths") @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','INSTRUCTOR','ORG_ADMIN')") public ApiResponse<Map<String,Object>> path(@PathVariable UUID programId,@Valid @RequestBody CreateLearningPathRequest r){var p=programs.findWithOrganizationById(programId).orElseThrow(()->new EntityNotFoundException("Program not found"));assertManageable(p); var lp=paths.save(new LearningPath(p,r.title(),r.description()));return ApiResponse.success("Learning path created",Map.of("id",lp.getId(),"title",lp.getTitle()));}
 @PostMapping("/paths/{pathId}/courses") @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','INSTRUCTOR','ORG_ADMIN')") public ApiResponse<Map<String,Object>> addCourse(@PathVariable UUID pathId,@Valid @RequestBody AddCourseToPathRequest r){var lp=paths.findWithProgramAndOrganizationById(pathId).orElseThrow(()->new EntityNotFoundException("Learning path not found"));var c=courses.findById(r.courseId()).orElseThrow(()->new EntityNotFoundException("Course not found"));var p=lp.getProgram();assertManageable(p);assertCourseOrganizationMatchesProgram(p,c); var pc=pathCourses.save(new LearningPathCourse(lp,c,r.sortOrder()));return ApiResponse.success("Course added to learning path",Map.of("id",pc.getId()));}
 @GetMapping("/{programId}/detail") @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','INSTRUCTOR','ORG_ADMIN')") public ApiResponse<Map<String,Object>> detail(@PathVariable UUID programId){var p=programs.findWithOrganizationById(programId).orElseThrow(()->new EntityNotFoundException("Program not found"));assertManageable(p);var links=pathCourses.findByLearningPathProgramIdOrderByLearningPathTitleAscSortOrderAsc(programId);var pathsById=new LinkedHashMap<UUID,Map<String,Object>>();for(var link:links){var lp=link.getLearningPath();var path=pathsById.computeIfAbsent(lp.getId(),id->{var m=new LinkedHashMap<String,Object>();m.put("id",lp.getId());m.put("title",lp.getTitle());m.put("description",lp.getDescription()==null?"":lp.getDescription());m.put("courses",new ArrayList<Map<String,Object>>());return m;});@SuppressWarnings("unchecked") var pathCoursesList=(ArrayList<Map<String,Object>>)path.get("courses");var course=link.getCourse();var cm=new LinkedHashMap<String,Object>();cm.put("id",course.getId());cm.put("title",course.getTitle());cm.put("slug",course.getSlug());cm.put("description",course.getDescription()==null?"":course.getDescription());cm.put("status",course.getStatus().name());cm.put("sortOrder",link.getSortOrder());cm.put("organizationId",course.getOrganization()==null?null:course.getOrganization().getId());pathCoursesList.add(cm);}var data=new LinkedHashMap<String,Object>();data.put("id",p.getId());data.put("title",p.getTitle());data.put("slug",p.getSlug());data.put("description",p.getDescription()==null?"":p.getDescription());data.put("status",p.getStatus().name());data.put("organizationId",p.getOrganization()==null?null:p.getOrganization().getId());data.put("learningPathCount",pathsById.size());data.put("courseCount",links.size());data.put("learningPaths",new ArrayList<>(pathsById.values()));return ApiResponse.success("Program detail retrieved",data);}
 @PutMapping("/{programId}/publish") @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','INSTRUCTOR','ORG_ADMIN')") public ApiResponse<Map<String,Object>> publish(@PathVariable UUID programId){var p=findManageable(programId);p.publish();return state("Program published",p);}
 @PutMapping("/{programId}/start") @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','INSTRUCTOR','ORG_ADMIN')") public ApiResponse<Map<String,Object>> start(@PathVariable UUID programId){var p=findManageable(programId);p.start();return state("Program started",p);}
 @PutMapping("/{programId}/pause") @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','INSTRUCTOR','ORG_ADMIN')") public ApiResponse<Map<String,Object>> pause(@PathVariable UUID programId){var p=findManageable(programId);p.pause();return state("Program paused",p);}
 @PutMapping("/{programId}/resume") @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','INSTRUCTOR','ORG_ADMIN')") public ApiResponse<Map<String,Object>> resume(@PathVariable UUID programId){var p=findManageable(programId);p.resume();return state("Program resumed",p);}
 @PutMapping("/{programId}/complete") @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','INSTRUCTOR','ORG_ADMIN')") public ApiResponse<Map<String,Object>> complete(@PathVariable UUID programId){var p=findManageable(programId);p.complete();return state("Program completed",p);}
 @PutMapping("/{programId}/archive") @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','INSTRUCTOR','ORG_ADMIN')") public ApiResponse<Map<String,Object>> archive(@PathVariable UUID programId){var p=findManageable(programId);p.archive();return state("Program archived",p);}
 private void assertManageable(Program p){ if (isSuperAdmin()) return; if (p.getOrganization()==null || !organizationAuthorization.canAccessOrganization(p.getOrganization().getId())) throw new AccessDeniedException("You do not have access to this organization program"); }
 private void assertCourseOrganizationMatchesProgram(Program p, com.masterlearning.platform.modules.course.entity.Course c){ if (p.getOrganization()==null) return; var programOrganizationId=p.getOrganization().getId(); var courseOrganization=c.getOrganization(); if (courseOrganization==null || !programOrganizationId.equals(courseOrganization.getId())) throw new AccessDeniedException("Course organization does not match program organization"); }
 private boolean isSuperAdmin(){ var auth=SecurityContextHolder.getContext().getAuthentication(); return auth!=null && auth.getAuthorities().stream().anyMatch(a->"ROLE_SUPER_ADMIN".equals(a.getAuthority())); }
 private Program findManageable(UUID programId){var p=programs.findById(programId).orElseThrow(()->new EntityNotFoundException("Program not found"));if(!isSuperAdmin() && (p.getOrganization()==null || !organizationAuthorization.canAccessOrganization(p.getOrganization().getId())))throw new AccessDeniedException("You do not have access to this organization program");return p;}
 private ApiResponse<Map<String,Object>> state(String message,Program p){return ApiResponse.success(message,Map.of("id",p.getId(),"title",p.getTitle(),"status",p.getStatus().name()));}
}