package com.masterlearning.platform.modules.program.controller;
import com.masterlearning.platform.common.api.ApiResponse; import com.masterlearning.platform.modules.program.dto.request.*; import com.masterlearning.platform.modules.program.entity.*; import com.masterlearning.platform.modules.program.repository.*; import com.masterlearning.platform.modules.organization.repository.OrganizationRepository; import com.masterlearning.platform.modules.course.repository.CourseRepository; import jakarta.persistence.EntityNotFoundException; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/v1/programs") public class ProgramController {
 private final ProgramRepository programs; private final LearningPathRepository paths; private final LearningPathCourseRepository pathCourses; private final OrganizationRepository organizations; private final CourseRepository courses;
 public ProgramController(ProgramRepository p,LearningPathRepository lp,LearningPathCourseRepository lpc,OrganizationRepository o,CourseRepository c){programs=p;paths=lp;pathCourses=lpc;organizations=o;courses=c;}
 @PostMapping @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','INSTRUCTOR')") public ApiResponse<Map<String,Object>> create(@Valid @RequestBody CreateProgramRequest r){if(programs.findBySlug(r.slug()).isPresent())throw new IllegalArgumentException("Program slug already exists");var o=r.organizationId()==null?null:organizations.findById(r.organizationId()).orElseThrow(()->new EntityNotFoundException("Organization not found"));var p=programs.save(new Program(r.title(),r.slug(),r.description(),o));return ApiResponse.success("Program created",Map.of("id",p.getId(),"title",p.getTitle()));}
 @PostMapping("/{programId}/paths") @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','INSTRUCTOR')") public ApiResponse<Map<String,Object>> path(@PathVariable UUID programId,@Valid @RequestBody CreateLearningPathRequest r){var p=programs.findById(programId).orElseThrow(()->new EntityNotFoundException("Program not found"));var lp=paths.save(new LearningPath(p,r.title(),r.description()));return ApiResponse.success("Learning path created",Map.of("id",lp.getId(),"title",lp.getTitle()));}
 @PostMapping("/paths/{pathId}/courses") @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','INSTRUCTOR')") public ApiResponse<Map<String,Object>> addCourse(@PathVariable UUID pathId,@Valid @RequestBody AddCourseToPathRequest r){var lp=paths.findById(pathId).orElseThrow(()->new EntityNotFoundException("Learning path not found"));var c=courses.findById(r.courseId()).orElseThrow(()->new EntityNotFoundException("Course not found"));var pc=pathCourses.save(new LearningPathCourse(lp,c,r.sortOrder()));return ApiResponse.success("Course added to learning path",Map.of("id",pc.getId()));}
 @PutMapping("/{programId}/publish") @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','INSTRUCTOR')") public ApiResponse<Map<String,Object>> publish(@PathVariable UUID programId){var p=programs.findById(programId).orElseThrow(()->new EntityNotFoundException("Program not found"));p.publish();return ApiResponse.success("Program published",Map.of("id",p.getId(),"status",p.getStatus().name()));}
}