package com.masterlearning.platform.bootstrap;

import com.masterlearning.platform.modules.user.entity.User;
import com.masterlearning.platform.modules.user.repository.UserRepository;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Repairs the seeded local test student's password using the application's
 * actual PasswordEncoder. This is intentionally active only for the local profile.
 */
@Component
@Profile("local")
public class LocalStudentCredentialRepair implements ApplicationRunner {

    private static final String STUDENT_EMAIL = "student@masterlearning.local";
    private static final String LOCAL_STUDENT_PASSWORD = "password";

    // Hashes used by the original seed/repair migrations. They are intentionally
    // listed only as migration-repair markers; a new hash is generated by Spring.
    private static final String ORIGINAL_SEED_HASH =
            "$2a$10$nypRayemMzfjq34uR4vjXOGzDS3FB8PkS5pgEizvOZ4vpWf/ilvX2";
    private static final String MIGRATION_REPAIR_HASH =
            "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy";

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    public LocalStudentCredentialRepair(
            UserRepository userRepository,
            PasswordEncoder passwordEncoder
    ) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
    }

    @Override
    @Transactional
    public void run(ApplicationArguments args) {
        userRepository.findByEmailIgnoreCase(STUDENT_EMAIL).ifPresent(this::repairIfNeeded);
    }

    private void repairIfNeeded(User user) {
        String currentHash = user.getPasswordHash();

        if (!ORIGINAL_SEED_HASH.equals(currentHash)
                && !MIGRATION_REPAIR_HASH.equals(currentHash)) {
            return;
        }

        user.updatePasswordHash(passwordEncoder.encode(LOCAL_STUDENT_PASSWORD));
        user.enable();
        userRepository.saveAndFlush(user);
    }
}
