package com.masterlearning.platform.core.auth;
import com.masterlearning.platform.core.security.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.Instant; import java.util.*; import static com.masterlearning.platform.core.auth.AuthDtos.*;
@Service
public class AuthService {
 private final UserRepository users; private final RoleRepository roles; private final RefreshTokenRepository refresh; private final PasswordEncoder encoder; private final JwtService jwt; private final SecurityProperties p;
 public AuthService(UserRepository u,RoleRepository r,RefreshTokenRepository t,PasswordEncoder e,JwtService j,SecurityProperties p){users=u;roles=r;refresh=t;encoder=e;jwt=j;this.p=p;}
 @Transactional public void register(RegisterRequest q){String email=EmailNormalizer.normalize(q.email());if(users.existsByEmailIgnoreCase(email))throw new IllegalArgumentException("Email already registered");User u=new User(email,encoder.encode(q.password()),q.firstName().trim(),q.lastName());roles.findByCode("STUDENT").ifPresent(u::addRole);users.save(u);}
 @Transactional public AuthResponse login(LoginRequest q,String ua,String ip){User u=users.findByEmailIgnoreCase(EmailNormalizer.normalize(q.email())).orElseThrow(()->new IllegalArgumentException("Invalid credentials"));if(u.isLocked())throw new IllegalArgumentException("Account is temporarily locked");if(!encoder.matches(q.password(),u.getPasswordHash())){u.recordFailedLogin(p.login().maxAttempts(),p.login().lockMinutes());users.save(u);throw new IllegalArgumentException("Invalid credentials");}if(u.getStatus()!=UserStatus.ACTIVE)throw new IllegalArgumentException("Account is not active");u.recordLogin();return issue(u,UUID.randomUUID(),ua,ip);}
 @Transactional public AuthResponse rotate(String raw,String ua,String ip){RefreshToken old=refresh.findByTokenHash(hash(raw)).orElseThrow(()->new IllegalArgumentException("Invalid refresh token"));if(!old.isUsable()){for(RefreshToken t:refresh.findByFamilyId(old.getFamilyId()))t.revoke();throw new IllegalArgumentException("Refresh token expired or revoked");}old.used();old.revoke();return issue(old.getUser(),old.getFamilyId(),ua,ip);}
 @Transactional public void logout(String raw){refresh.findByTokenHash(hash(raw)).ifPresent(t->{for(RefreshToken x:refresh.findByFamilyId(t.getFamilyId()))x.revoke();});}
 private AuthResponse issue(User u,UUID family,String ua,String ip){String raw=random();Instant exp=Instant.now().plusSeconds(p.jwt().refreshTokenDays()*86400L);refresh.save(new RefreshToken(u,hash(raw),family,exp,ua,ip));return new AuthResponse(jwt.accessToken(u),raw,"Bearer",p.jwt().accessTokenMinutes()*60L,u.getId(),u.getEmail());}
 private String random(){byte[] b=new byte[48];new SecureRandom().nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}
 private String hash(String s){try{return Base64.getEncoder().encodeToString(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}